name: Build & Publish Docker Image

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Set environment variables
      run: echo RELEASE=$(cat ./package.json | jq -r .release) >> $GITHUB_ENV
    
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: ghcr.io/weejewel/google-backup:latest, ghcr.io/weejewel/google-backup:${{ env.RELEASE }}
